- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure the system is up to date
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
    - name: Ensure the system is up to date
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
  tasks:
    - name: Include the role
      ansible.builtin.include_role:
        name: ansible-role-template
